Add 3 questions and move question order
Taewan-P/workshop-validator pull request #2
Opened 2021-01-21 06:49 UTC by jil8885

- 이슈를 생성하는 문제
- 이슈에 Assignee와 Label을 달아보는 문제 추가
- 문제 순서 수정

2021-01-21 07:09 UTC, Taewan-P requested changes

2021-01-21 07:09 UTC, Taewan-P commented on workshop_validator/main/views.py
> +    Do a hard reset to your repository. Revert all commits after the Pull Request you've made.
주석 수정해주세용

2021-01-21 07:09 UTC, Taewan-P commented on workshop_validator/main/templates/main/question10.html
> +			<li><span>되돌리고 남은 commit 중 제일 최신 커밋의 일련번호를 입력할 것.</span></li>
일련번호라고 하지말고 Commit ID(SHA)라고 하는게 좋을듯? 다른 의견 있음?

2021-01-22 00:13 UTC, jil8885 commented
해당 Review에 대한 수정을 진행했습니다

2021-01-22 00:31 UTC, Taewan-P approved these changes

2021-01-22 00:31 UTC, merged